plugins {
    id "com.android.application"
}

android {
    namespace "com.daicg.hearingaid"
    compileSdk 35

    defaultConfig {
        applicationId "com.daicg.hearingaid"
        minSdk 26
        targetSdk 35
        versionCode 71
        versionName "wired-stable-1.4"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
